<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="FB_ESP01" Id="{63d8bd01-3f15-4424-afa2-cf6d4ee1f766}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ESP01
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	fbESPNow : FB_ESPNow;
	fbSerialCom : FB_SerialCom; 
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>