<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="FB_TemperatureSensor" Id="{aa82beeb-f8d4-4ab1-8220-d0c7217097c1}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_TemperatureSensor
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>