<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="FB_AirConditionerBase" Id="{8a14cb96-ec1e-44a6-964e-020b0d9869d0}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT FB_AirConditionerBase EXTENDS FB_Device
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="TurnOff" Id="{63713da6-a9b0-4c78-8811-764f20c72265}">
      <Declaration><![CDATA[METHOD TurnOff : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="TurnOn" Id="{19db32a1-132c-4ed7-96f3-ecd21742b63a}">
      <Declaration><![CDATA[METHOD TurnOn : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>